### ISSUE TITLE
精度问题

### ISSUE THREAD

**Issue by zhangxiaopang88** [rshaojimmy/AAAI2020-RFMetaFAS#13]
您好，我按照您的要求送入网络rgb人脸图片，但是不管是real还是fake的样本，分数都在0.5左右，没有大的变化。请问您遇到过这种问题吗？ @ @rshaojimmy

**Comment by rshaojimmy** [comment]
您好，我没遇到过这种情况。然后输入是RGB + HSV 而不是 RGB。
谢谢

**Comment by zhangxiaopang88** [comment]
ori_catimg = torch.cat([ori_rgbimg,ori_hsvimg],0)
这个函数的意思不是输入rgb图片，转换成hsv，然后把rgb和hsv 一起送入网络吗？我输入rgb图片，网络的输入也是RGB + HSV啊，是不是我测试用的CASIA数据集不符合训练的要求啊 @ @rshaojimmy

**Comment by roger-cv** [comment]
> ori_catimg = torch.cat([ori_rgbimg,ori_hsvimg],0)
> 这个函数的意思不是输入rgb图片，转换成hsv，然后把rgb和hsv 一起送入网络吗？我输入rgb图片，网络的输入也是RGB + HSV啊，是不是我测试用的CASIA数据集不符合训练的要求啊 @ @rshaojimmy

您好，请问您成功复现这篇论文的代码了吗？我想请问一些关于数据预处理的问题，我可以通过邮箱或者其他方式联系您吗？谢谢

**Comment by duzhekai** [comment]
> 您好，我按照您的要求送入网络rgb人脸图片，但是不管是real还是fake的样本，分数都在0.5左右，没有大的变化。请问您遇到过这种问题吗？ @ @rshaojimmy

你好，请问你解决这个问题了吗，我也是出现分数都在0.5左右的问题。
