### ISSUE TITLE
fake_depth.jpg

### ISSUE THREAD

**Issue by Aurasy** [rshaojimmy/AAAI2020-RFMetaFAS#16]
您可以提供一下fake_depth.jpg吗，所有假脸的深度是不是都假设为0了，那么您在训练的过程中用的fake_depth.jpg是什么样的呢，可以描述一下吗

**Comment by rshaojimmy** [comment]
Hi，

训练的时候fake_depth.jpg统一都是全0的像素点的图片。

谢谢

**Comment by Aurasy** [comment]
感谢回答！还有个问题想请教一下~ 运行DatasetLoader.py的时候总是不能调用  __getitem__(self, index)，但是self.imgs是正常非空的，这是什么原因呢

**Comment by rshaojimmy** [comment]
__getitem__是类定义的方法，自动就调用的。但是没有办法通过断点进去调试。

**Comment by Aurasy** [comment]
您好，深度图是32×32，RGB是256×256大小吗，谢谢回答~

**Comment by rshaojimmy** [comment]
是的。谢谢。

**Comment by roger-cv** [comment]
@rshaojimmy 您好，请问valid和test时，攻击样本的ground-truth也是使用全黑的32x32的深度图吗？另外，test过后，生成.h5文件，我们需要怎么处理才能得到正常的HTER和AUC值呢？
