### ISSUE TITLE
Error encountered running "python main.py --training_type Test"

### ISSUE THREAD

**Issue by Benjamin-YKH** [rshaojimmy/AAAI2020-RFMetaFAS#17]
Hi,

Thanks for sharing your code.
I have installed and setup the prerequisite software.
However when I run the Testing mode using this command "python main.py --training_type Test", I encountered the following error. The program main.py seems to be asking for the command line argument parameter tstfile. 
Appreciate your advice. Thanks

File "main.py", line 175, in <module>
    main(parser.parse_args())
File "main.py", line 22, in main
    savefilename = osp.join(args.tstfile, args.tstdataset+'to'+args.dataset_target+args.snapshotnum)
AttributeError: 'Namespace' object has no attribute 'tstfile'

Best Regards,
Benjamin

**Comment by rshaojimmy** [comment]
Hi,

You need to set your tstfile in the command line according to the folder containing your saved model.

Thanks.
