### ISSUE TITLE
Questions about project details

### ISSUE THREAD

**Issue by Dnlee17** [rshaojimmy/AAAI2020-RFMetaFAS#21]
Hi,
thanks for sharing the code.
I have some questions about your project that I would like to confirm.
1.What did your meta learner mainly learn?(FeatExtractor Weight or some hyperparameters?)
2.When testing, is it not necessary to generate a face depth map? because it is only used to auxiliary supervision, like an image label?
3.we need to generate a depth map through PRNet and add it to the input ? or your code contains this generate function?
4.Is it possible to achieve real-time detection?

Thanks.

**Comment by rshaojimmy** [comment]
Hi,

Thanks for your interest in our work!

1. meta learner only carries out meta-learning to update its own parameters.
2. It is not necessary to generate a face depth map during testing. Yes, it has a similar function as image label as the role of auxiliary supervision.
3. The face depth map is generated for each corresponding input image in advance offline with codes in the repo: https://github.com/YadiraF/PRNet.
4. I think it could try to be deployed in real-time detection.

Thanks.
