### ISSUE TITLE
why the hsv image also as the input?

### ISSUE THREAD

**Issue by sicong-li** [rshaojimmy/AAAI2020-RFMetaFAS#3]
i see the hsv image also as the input in your code, and don't mark it in your paper . can you tell me what information dose hsv image can provide?

**Comment by rshaojimmy** [comment]
Hi, 

please refer to the supplementary material of our paper which has mentioned that the HSV channels are also the input. Many face anti-spoofing papers have also considered the HSV channels as the input. RGB combined with HSV can provide more sufficient differentiation cues for the task of face anti-spoofing.

Thanks.
