### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by ghost** [rshaojimmy/AAAI2020-RFMetaFAS#5]
Hi, a great job. But when I reuse your code to trian model by myself, I encounter the following problems:

1. **I find the model is too large, and when training, the results are very shocking**. For example, when I use the epoch100 trained_model to test, the ACC in testing-set is 80%, but when I use the epoch101 trained_model to test, the ACC in testing-set is below 60%. Do you know why?

2. **I cannot reproduce the results of the C&I&M to O scenario in your paper**. The best AUC results that I achieved by using your code is 82%, which has a large gap compared to the results published in your paper 91.16%. How do you test your model on Oulu dataset? Do you use the all data (training and testing) or just the testing data? Why I cannot reproduce the results? 

Thank you very much!!

**Comment by rshaojimmy** [comment]
Hi,

1. Please note that we did the early-stopping based on the test performance of the trained model.

2. We use all the data (including training and testing) in the Oulu dataset to do the testing.

Thanks.

**Comment by roger-cv** [comment]
> Hi, a great job. But when I reuse your code to trian model by myself, I encounter the following problems:
> 
> 1. **I find the model is too large, and when training, the results are very shocking**. For example, when I use the epoch100 trained_model to test, the ACC in testing-set is 80%, but when I use the epoch101 trained_model to test, the ACC in testing-set is below 60%. Do you know why?
> 2. **I cannot reproduce the results of the C&I&M to O scenario in your paper**. The best AUC results that I achieved by using your code is 82%, which has a large gap compared to the results published in your paper 91.16%. How do you test your model on Oulu dataset? Do you use the all data (training and testing) or just the testing data? Why I cannot reproduce the results?
> 
> Thank you very much!!



> Hi, a great job. But when I reuse your code to trian model by myself, I encounter the following problems:
> 
> 1. **I find the model is too large, and when training, the results are very shocking**. For example, when I use the epoch100 trained_model to test, the ACC in testing-set is 80%, but when I use the epoch101 trained_model to test, the ACC in testing-set is below 60%. Do you know why?
> 2. **I cannot reproduce the results of the C&I&M to O scenario in your paper**. The best AUC results that I achieved by using your code is 82%, which has a large gap compared to the results published in your paper 91.16%. How do you test your model on Oulu dataset? Do you use the all data (training and testing) or just the testing data? Why I cannot reproduce the results?
> 
> Thank you very much!!

I am confused about the path processing of the data txt file. Can you share the specific path format of the txt file? Thank you!
