### ISSUE TITLE
Ask for the code

### ISSUE THREAD

**Issue by ReedZyd** [rshaojimmy/AAAI2020-RFMetaFAS#6]
I am sorry for the inconveninent I have caused. I would like to ask, do you reproduce the code of MetaReg？

**Comment by rshaojimmy** [comment]
Hello,

We implement the method of MetaReg by ourselves since no reply from the author of MetaReg is given for the request about the official codes.

Thanks.

**Comment by ReedZyd** [comment]
Can you share it? Thank you very much.
