### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by shanjianwu** [rshaojimmy/AAAI2020-RFMetaFAS#8]
I have some questions about the code In datasets/DatasetLoader.py :
```
if getreal:
            filename = 'image_list_real.txt'
        else:
            filename = 'image_list_fake.txt'
```
What's the content in image_list_real.txt about and how do you get these files?
I cannot get these files after I download the datasets so I am curious about it.

**Comment by rshaojimmy** [comment]
Hi,

These text files contain the directory of real and fake face frames extracted from the corresponding videos. You could just extract the frames from the videos and make your own directory.

Thanks.

**Comment by shanjianwu** [comment]
Thanks for your answer!

**Comment by shanjianwu** [comment]
Can you show me some examples of image_list_real.txt? I'd like to know how it's built.

**Comment by Shijia-Guo** [comment]
if getreal == False , what's the depth_dir is?

**Comment by roger-cv** [comment]
> Can you show me some examples of image_list_real.txt? I'd like to know how it's built.

Do you know about the path processing of the data txt file? Can you share the specific path format of the txt file? Thank you!
